version: '2'
services:
    konga:
        image: pantsel/konga
        environment:
            - NODE_ENV=development
        ports:
            - "1337:1337"
        expose:
            - "1337"
        links:
            - kong:kong
        depends_on:
            - kong
    kong:
        image: kong
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "7946:7946"
            - "7946:7946/udp"
        expose:
            - "8000"
            - "8443"
            - "8001"
        links:
            - kong-database:kong-database

        depends_on:
            - kong-database

    kong-database:
        image: postgres:9.4
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
        ports:
            - "5432:5432"
        expose:
            - "5432"